### ISSUE TITLE
Error - JSON file 'data/in-network-rates-fee-for-service-sample.json' not found

### ISSUE THREAD

**Issue by vijayanandramamoorthy** [CMSgov/price-transparency-guide-validator#46]
I am unable to get the validator working. When I run the 
**_cms-mrf-validator validate test-files/in-network-rates-fee-for-service-sample.json v1.0.0_**
command i get a JSON file 'data/in-network-rates-fee-for-service-sample.json' not found error. The file is present in the test_files folder. Not sure why the validator adds "data/" to the path.

At work, we have Docker CLI, but not Docker Desktop. Also, we are running the validator on a Linux (RHEL) machine.
At home, I was able to run the validator using Docker Desktop on a windows machine, without any issues.

Any ideas on how to resolve this issue?

thanks

**Comment by mint-thompson** [comment]
Thank you for reporting this issue. The reason for the "data/" at the beginning of the path is because the path reported in this error message is produced inside the Docker container that is running the validator. As a result, the error message you receive is not as helpful as it could be. To make this easier to troubleshoot, the validator will be updated to check the path to the data file before sending the path to the Docker container.

**Comment by vijayanandramamoorthy** [comment]
Thank you for the quick response. After the update,  if the path to data file is a valid one (which it is), then I should expect to see a different error message from the validator?
