### ISSUE TITLE
Validating locally is slow

### ISSUE THREAD

**Issue by cigzigwon** [CMSgov/price-transparency-guide-validator#72]
I have a 25.35GB MRF file with NPI arrays containing 200-1000 NPIs in each in-network rates row. I don't think this is benchmarked to a realistic MRF (Files for Large Health Network). I have the file and validating for 10hours locally (2.6 GHz 6-Core Intel Core i7 - 32 GB 2400 MHz DDR4).

This does not seem to align with the consumption rate outlined and it's also containerized so it's not leveraging my cores (Don't know if program does). When we have to consider costs in cloud to build a service we could double the power and I don't think that we could get 25MB/s in the validator.

To build these files I have to stream write them to disk and then compose several files into one. Then it gets validated. At this rate I have to start processing files for 10/1 and bucket 48hours of processing time to get a file out. 

Is there any improvements you can make here? Suggestions? I think we are both having a similar issue except to parse those arrays from a map (Elixir) and stream to a string on disk and I'm pushing %300 CPU consumption and %6 in memory. What I would like to do is throw away your validator and just consume the schema into my own program in Elixir. Can we do that?

**Comment by cigzigwon** [comment]
This is unacceptable. I'm into hour 39 on a MacBook Pro as I've outlined. This is a stop gap here. I have built a file an AMZN T.micro instance in about 34 hours. So I can't expect to build/validate/push something in (34 + 39 + ??? + loss of processing power time locally). I think you need to re-consider your benchmark or do it against a bigger file. I plan on moving this to a compute box but have to incur costs up front get a realistic idea of throughput because it is nowhere near what is being reported. We are doing business.

**Comment by cigzigwon** [comment]
In my mind my server thats building the files (SLOW) should not be outpacing a machine thats way faster in validating them locally...

**Comment by shaselton-usds** [comment]
Hey @cigzigwon -- thanks for reaching out. 

Just to get it out of the way, you're correct, 39 hours (or anything even remotely close to that) is absurd. 

I've been able to validate a 10 gig file locally (as well as on a 100 gig file on AWS) on my m1 macbook at roughly the rate of 25 MB/sec -- so roughly 6.5 minutes to get through the whole file. The RAM/memory wasn't much of an issue due to the validator built to stream the input for validation vs trying to load the entire dataset into memory.

Containerization was meant to support multiple architectures (as you know), so I can run this on my m1 while others can run it on their x86s, etc.

I'm not 100% sure what restrictions you have in place in terms of leveraging this validator vs doing it yourself via Elixir -- this tool is only meant to be a helper and there are not requirements to use it. If you find it unhelpful, by all means, figure out something else that works best for you.

It would be helpful if you were to point to the file in question if possible.

**Comment by cigzigwon** [comment]
This advice helps a lot. The validator does help with exposing issues in the JSON, I just didn't expect to run into this issue when running locally w/this file. I have since pushed the file but it took like 57 hours to complete.

Here is the file in cloud: [https://mrfcentral.com/2022-09-01_First-Health-Network_in-network-rates.json](https://mrfcentral.com/2022-09-01_First-Health-Network_in-network-rates.json)
